# apiVersion: v1
# kind: Service
# metadata:
#   name: backend
#   namespace: bookstore
# spec:
#   selector:
#     app: backend
#   ports:
#   - port: 5050
#     targetPort: 5050
#   type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: bookstore
spec:
  selector:
    app: backend
  ports:
  - port: 5050
    targetPort: 5050
    nodePort: 30050
  type: NodePort