# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
#   namespace: bookstore
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#       - name: backend
#         image: bookstore-backend:latest
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 5050
#         env:
#         - name: MONGO_URI
#           value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb:27017/$(DATABASE_NAME)?authSource=admin"
#         - name: SECRET_KEY
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: flask-secret
#         - name: MONGO_USERNAME
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: username
#         - name: MONGO_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: password
#         - name: DATABASE_NAME
#           valueFrom:
#             configMapKeyRef:
#               name: backend-config
#               key: DATABASE_NAME
#         - name: FLASK_APP
#           value: "app.py"
#         - name: FLASK_RUN_HOST
#           value: "0.0.0.0"


apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bookstore-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: flask-secret
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_NAME
        - name: MONGO_URI
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb:27017/bookstore?authSource=admin"
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"