apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: bookstore
type: Opaque
data:
  # Use base64 encoded values: echo -n "admin" | base64
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQxMjM=  # password123
  flask-secret: c3VwZXJzZWNyZXQ=  # supersecret
